### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-12-18/jsorrell#1]
Please push your latest assignments.

**Comment by dojo-json** [comment]
Updates needed please.

**Comment by jfsorrell** [comment]
Hi Jason!

I will be jumping on it getting assignments in today. On the 18th, a
student hit me in the face with an orange at work and triggered some
terrible migraines that plagued me last week (I was out of work all of last
week). I’ve returned to my job Monday and I’ve been multitasking catching
up on work and working on my coding. Sorry for the hiatus.
